/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mailbox = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const CalendarEventRole = IDL.Variant({
  'optional' : IDL.Null,
  'notParticipating' : IDL.Null,
  'chair' : IDL.Null,
  'required' : IDL.Null,
});
export const Attendee = IDL.Record({
  'who' : Mailbox,
  'role' : CalendarEventRole,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CalendarEventMethod = IDL.Variant({
  'request' : IDL.Null,
  'publish' : IDL.Null,
  'cancel' : IDL.Null,
});
export const CalendarEvent = IDL.Record({
  'uid' : IDL.Text,
  'startTime' : IDL.Nat64,
  'method' : CalendarEventMethod,
  'organizer' : Mailbox,
  'endTime' : IDL.Nat64,
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'attendees' : IDL.Vec(Attendee),
  'location' : IDL.Text,
  'sequence' : IDL.Nat32,
});

export const idlService = IDL.Service({
  'addCalendarEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
      [],
      [],
    ),
  'addEventAttendees' : IDL.Func([IDL.Text, IDL.Vec(Attendee)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelEvent' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIntegrationsCanisterId' : IDL.Func([], [IDL.Text], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeEventAttendees' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendEventInvitation' : IDL.Func([IDL.Text], [], []),
  'updateEventDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
        IDL.Opt(IDL.Nat64),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mailbox = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const CalendarEventRole = IDL.Variant({
    'optional' : IDL.Null,
    'notParticipating' : IDL.Null,
    'chair' : IDL.Null,
    'required' : IDL.Null,
  });
  const Attendee = IDL.Record({ 'who' : Mailbox, 'role' : CalendarEventRole });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CalendarEventMethod = IDL.Variant({
    'request' : IDL.Null,
    'publish' : IDL.Null,
    'cancel' : IDL.Null,
  });
  const CalendarEvent = IDL.Record({
    'uid' : IDL.Text,
    'startTime' : IDL.Nat64,
    'method' : CalendarEventMethod,
    'organizer' : Mailbox,
    'endTime' : IDL.Nat64,
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'attendees' : IDL.Vec(Attendee),
    'location' : IDL.Text,
    'sequence' : IDL.Nat32,
  });
  
  return IDL.Service({
    'addCalendarEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64, IDL.Nat64],
        [],
        [],
      ),
    'addEventAttendees' : IDL.Func([IDL.Text, IDL.Vec(Attendee)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelEvent' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIntegrationsCanisterId' : IDL.Func([], [IDL.Text], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeEventAttendees' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendEventInvitation' : IDL.Func([IDL.Text], [], []),
    'updateEventDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
          IDL.Opt(IDL.Nat64),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };