/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendee { 'who' : Mailbox, 'role' : CalendarEventRole }
export interface CalendarEvent {
  'uid' : string,
  'startTime' : bigint,
  'method' : CalendarEventMethod,
  'organizer' : Mailbox,
  'endTime' : bigint,
  'description' : string,
  'summary' : string,
  'attendees' : Array<Attendee>,
  'location' : string,
  'sequence' : number,
}
export type CalendarEventMethod = { 'request' : null } |
  { 'publish' : null } |
  { 'cancel' : null };
export type CalendarEventRole = { 'optional' : null } |
  { 'notParticipating' : null } |
  { 'chair' : null } |
  { 'required' : null };
export interface Mailbox { 'name' : [] | [string], 'email' : string }
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addCalendarEvent' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'addEventAttendees' : ActorMethod<[string, Array<Attendee>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelEvent' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIntegrationsCanisterId' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'removeEventAttendees' : ActorMethod<[string, Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendEventInvitation' : ActorMethod<[string], undefined>,
  'updateEventDetails' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];