/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Attendee {
    who: Mailbox;
    role: CalendarEventRole;
}
export interface CalendarEvent {
    uid: string;
    startTime: bigint;
    method: CalendarEventMethod;
    organizer: Mailbox;
    endTime: bigint;
    description: string;
    summary: string;
    attendees: Array<Attendee>;
    location: string;
    sequence: number;
}
export interface Mailbox {
    name?: string;
    email: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum CalendarEventMethod {
    request = "request",
    publish = "publish",
    cancel = "cancel"
}
export enum CalendarEventRole {
    optional = "optional",
    notParticipating = "notParticipating",
    chair = "chair",
    required = "required"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addCalendarEvent(summary: string, description: string, location: string, startTimeMs: bigint, endTimeMs: bigint): Promise<void>;
    addEventAttendees(uid: string, attendees: Array<Attendee>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelEvent(uid: string): Promise<void>;
    deleteEvent(uid: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIntegrationsCanisterId(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listEvents(): Promise<Array<CalendarEvent>>;
    registerUser(name: string, email: string): Promise<void>;
    removeEventAttendees(uid: string, attendees: Array<string>): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendEventInvitation(uid: string): Promise<void>;
    updateEventDetails(uid: string, summary: string | null, description: string | null, location: string | null, startTimeMs: bigint | null, endTimeMs: bigint | null): Promise<void>;
}
import type { Attendee as _Attendee, CalendarEvent as _CalendarEvent, CalendarEventMethod as _CalendarEventMethod, CalendarEventRole as _CalendarEventRole, Mailbox as _Mailbox, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCalendarEvent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalendarEvent(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalendarEvent(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addEventAttendees(arg0: string, arg1: Array<Attendee>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEventAttendees(arg0, to_candid_vec_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEventAttendees(arg0, to_candid_vec_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async cancelEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelEvent(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getIntegrationsCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntegrationsCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntegrationsCanisterId();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return from_candid_vec_n13(this.uploadFile, this.downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async removeEventAttendees(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEventAttendees(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEventAttendees(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendEventInvitation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendEventInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendEventInvitation(arg0);
            return result;
        }
    }
    async updateEventDetails(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null, arg4: bigint | null, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEventDetails(arg0, to_candid_opt_n26(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n26(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n26(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n27(this.uploadFile, this.downloadFile, arg4), to_candid_opt_n27(this.uploadFile, this.downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEventDetails(arg0, to_candid_opt_n26(this.uploadFile, this.downloadFile, arg1), to_candid_opt_n26(this.uploadFile, this.downloadFile, arg2), to_candid_opt_n26(this.uploadFile, this.downloadFile, arg3), to_candid_opt_n27(this.uploadFile, this.downloadFile, arg4), to_candid_opt_n27(this.uploadFile, this.downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_Attendee_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Attendee): Attendee {
    return from_candid_record_n23(uploadFile, downloadFile, value);
}
function from_candid_CalendarEventMethod_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEventMethod): CalendarEventMethod {
    return from_candid_variant_n17(uploadFile, downloadFile, value);
}
function from_candid_CalendarEventRole_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEventRole): CalendarEventRole {
    return from_candid_variant_n25(uploadFile, downloadFile, value);
}
function from_candid_CalendarEvent_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarEvent): CalendarEvent {
    return from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_Mailbox_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mailbox): Mailbox {
    return from_candid_record_n19(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(uploadFile, downloadFile, value);
}
function from_candid_opt_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uid: string;
    startTime: bigint;
    method: _CalendarEventMethod;
    organizer: _Mailbox;
    endTime: bigint;
    description: string;
    summary: string;
    attendees: Array<_Attendee>;
    location: string;
    sequence: number;
}): {
    uid: string;
    startTime: bigint;
    method: CalendarEventMethod;
    organizer: Mailbox;
    endTime: bigint;
    description: string;
    summary: string;
    attendees: Array<Attendee>;
    location: string;
    sequence: number;
} {
    return {
        uid: value.uid,
        startTime: value.startTime,
        method: from_candid_CalendarEventMethod_n16(uploadFile, downloadFile, value.method),
        organizer: from_candid_Mailbox_n18(uploadFile, downloadFile, value.organizer),
        endTime: value.endTime,
        description: value.description,
        summary: value.summary,
        attendees: from_candid_vec_n21(uploadFile, downloadFile, value.attendees),
        location: value.location,
        sequence: value.sequence
    };
}
function from_candid_record_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: [] | [string];
    email: string;
}): {
    name?: string;
    email: string;
} {
    return {
        name: record_opt_to_undefined(from_candid_opt_n20(uploadFile, downloadFile, value.name)),
        email: value.email
    };
}
function from_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    who: _Mailbox;
    role: _CalendarEventRole;
}): {
    who: Mailbox;
    role: CalendarEventRole;
} {
    return {
        who: from_candid_Mailbox_n18(uploadFile, downloadFile, value.who),
        role: from_candid_CalendarEventRole_n24(uploadFile, downloadFile, value.role)
    };
}
function from_candid_variant_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: null;
} | {
    publish: null;
} | {
    cancel: null;
}): CalendarEventMethod {
    return "request" in value ? CalendarEventMethod.request : "publish" in value ? CalendarEventMethod.publish : "cancel" in value ? CalendarEventMethod.cancel : value;
}
function from_candid_variant_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    optional: null;
} | {
    notParticipating: null;
} | {
    chair: null;
} | {
    required: null;
}): CalendarEventRole {
    return "optional" in value ? CalendarEventRole.optional : "notParticipating" in value ? CalendarEventRole.notParticipating : "chair" in value ? CalendarEventRole.chair : "required" in value ? CalendarEventRole.required : value;
}
function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarEvent>): Array<CalendarEvent> {
    return value.map((x)=>from_candid_CalendarEvent_n14(uploadFile, downloadFile, x));
}
function from_candid_vec_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Attendee>): Array<Attendee> {
    return value.map((x)=>from_candid_Attendee_n22(uploadFile, downloadFile, x));
}
function to_candid_Attendee_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Attendee): _Attendee {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_CalendarEventRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEventRole): _CalendarEventRole {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
function to_candid_Mailbox_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mailbox): _Mailbox {
    return to_candid_record_n5(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_opt_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    who: Mailbox;
    role: CalendarEventRole;
}): {
    who: _Mailbox;
    role: _CalendarEventRole;
} {
    return {
        who: to_candid_Mailbox_n4(uploadFile, downloadFile, value.who),
        role: to_candid_CalendarEventRole_n6(uploadFile, downloadFile, value.role)
    };
}
function to_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    email: string;
}): {
    name: [] | [string];
    email: string;
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email
    };
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarEventRole): {
    optional: null;
} | {
    notParticipating: null;
} | {
    chair: null;
} | {
    required: null;
} {
    return value == CalendarEventRole.optional ? {
        optional: null
    } : value == CalendarEventRole.notParticipating ? {
        notParticipating: null
    } : value == CalendarEventRole.chair ? {
        chair: null
    } : value == CalendarEventRole.required ? {
        required: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Attendee>): Array<_Attendee> {
    return value.map((x)=>to_candid_Attendee_n2(uploadFile, downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
